apiRules:
- include:
    uidRegex: ^V8.UI.Elements
    type: Namespace
- include:
    uidRegex: ^V8.UI.Configuration
    type: Namespace
- include:
    uidRegex: ^V8.UI.Runtime
    type: Namespace
- include:
    uidRegex: ^V8.UI
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace