name: Example documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        run: docfx Documentation/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site

  deploy-docfx-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docfx-test Repository
        uses: actions/checkout@v2
        with:
          repository: hskim881028/docfx-test
          token: ${{ secrets.PAT }}
          ref: gh-pages

      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site

      - name: Deploy to docfx-test Repository
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          # /docs 디렉토리가 이미 존재하는지 확인하고, 존재한다면 제거
          rm -rf docs
          mkdir docs
          # 새 사이트 컨텐츠를 /docs 디렉토리로 복사
          cp -r _site/* docs/
          git add .
          git commit -m "Deploy DocFX Site to /docs"
          git push origin main
