name: Example documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Required by DocFX
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build
        run: docfx Documentation/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site

  deploy-docfx-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docfx-test Repository
        uses: actions/checkout@v2
        with:
          repository: hskim881028/docfx-test
          token: ${{ secrets.PAT }} # 여기서 PAT는 당신이 생성한 개인 접근 토큰

      - name: Download site artifact
        uses: actions/download-artifact@v1
        with:
          name: _site

      - name: Deploy to docfx-test Repository
        run: |
          cp -r _site/* . # _site 폴더의 내용을 루트 디렉토리로 복사
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Deploy DocFX Site"
          git push
